db:
  image: postgres

uwsgi:
  restart: always
  image: joke/neuropower
  command: /code/run_uwsgi.sh
  volumes:
    - .:/code
    - /var/www/static
  links:
    - db

nginx:
  restart: always
  image: nginx
  mem_limit: 60m
  ports:
    - "80:80"
  volumes:
    - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    - ./uwsgi_params.par:/etc/nginx/uwsgi_params.par:ro
  volumes_from:
    - uwsgi
  links:
    - uwsgi
